title: MemberCard System Documentation
description: Complete fuel management system with mobile and web interfaces

# Build settings
markdown: kramdown
highlighter: rouge

# Enable Mermaid support
kramdown:
  input: GFM
  hard_wrap: false